# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "feature/nodejs" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Make configuration file
      run: |
        echo "export const firebaseConfig = {" >> public/generous/js/firebase-config.js
        echo "  apiKey: \"${{secrets.API_KEY}}\"" >> /public/generous/js/firebase-config.js
        echo "  authDomain: \"${{secrets.AUTH_DOMAIN}}\"," >> generous/js/firebase-config.js
        echo "  projectId: \"${{secrets.PROJECT_ID}}\"," >> /generous/js/firebase-config.js
        echo "  storageBucket: \"${{secrets.STORAGE_BUCKET}}\"," >> js/firebase-config.js
        echo "  messagingSenderId: \"${{secrets.MESSAGING_SENDER_ID}}\"," >> /js/firebase-config.js
        echo "  appId: \"${{secrets.APP_ID}}\"," >> public/generous/js/firebase-config.js
        echo "  measurementId: \"${{secrets.MEASUREMENT_ID}}\"," >> public/generous/js/firebase-config.js
        echo "};" >> public/generous/js/firebase-config.js


    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm run build --if-present
